import os
import io
import zipfile
from typing import Dict, Any, List
from jinja2 import Environment, FileSystemLoader

class AssetsBuilder:
    def __init__(self, templates_dir: str = "templates"):
        self.env = Environment(loader=FileSystemLoader(templates_dir))

    def build_full_package(self, client_name: str, pdf_bytes: bytes, sections: List[Dict[str, Any]]) -> bytes:
        """
        Empaqueta el PDF, los artefactos Terraform, ADRs y el HTML de control
        en un solo archivo ZIP "Enterprise Grade".
        """
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # 1. Insertamos el Documento Maestro PDF
            zip_file.writestr("01_Executive_Dossier.pdf", pdf_bytes)
            
            # 2. Generamos Artefactos Técnicos -> Terraform
            terraform_main = self._generate_terraform_base(sections)
            zip_file.writestr("02_Technical_Assets/Terraform/main.tf", terraform_main)
            
            # Generamos Artefactos Técnicos -> ADR (Architecture Decision Record)
            adr_content = self._generate_adr(sections)
            zip_file.writestr("02_Technical_Assets/ADR/0001-cloud-strategy.md", adr_content)
            
            # 3. Generamos el Dashboard interactivo HTML
            dashboard_html = self._generate_dashboard(client_name, sections)
            zip_file.writestr("03_Interactive_Dashboard/index.html", dashboard_html)

            # 4. Generamos los Anexos (Excel Simulator, Checklist)
            roi_csv = self._generate_roi_csv(sections)
            zip_file.writestr("04_Enterprise_Annexes/ROI_Simulator_Export.csv", roi_csv)
            
            checklist = self._generate_checklist(sections)
            zip_file.writestr("04_Enterprise_Annexes/Implementation_Checklist.md", checklist)
            
        return zip_buffer.getvalue()

    def _generate_terraform_base(self, sections: List[Dict[str, Any]]) -> str:
        # Extraemos el contexto de la infraestructura metadata si existe
        infra = "t3.medium"
        region = "eu-west-1"
        for sec in sections:
            meta = sec.get("metadata", {})
            # We assume contextual data might be passed here or inside content somehow
            if "context" in meta:
               infra = meta["context"].get("infrastructure", infra)
               region = meta["context"].get("region", region)
               
        return f"""provider "aws" {{
  region = "{region}"
}}

# Auto-generated by AI Architect (Document Forge)
resource "aws_instance" "main" {{
  ami           = "ami-0c55b159cbfafe1f0" # Placeholder AMI
  instance_type = "{infra}"
  
  tags = {{
    Name = "Enterprise_Compute"
    ManagedBy = "DocumentForge"
  }}
}}

resource "aws_vpc" "main" {{
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
  
  tags = {{
    Name = "Enterprise_VPC"
    ManagedBy = "DocumentForge"
  }}
}}
"""

    def _generate_adr(self, sections: List[Dict[str, Any]]) -> str:
        # Extraer una posible recomendación/decisión del contexto
        recommendation = "Migrar workloads on-premise a instancias de Cloud Pública (AWS)."
        for sec in sections:
            if "content" in sec and "Recomendación" in sec["content"]:
                # simple heuristic for now
                recommendation = "Implementar recomendaciones propuestas en la sección de Análisis de Costes."

        return f"""# ADR 0001: Arquitectura y Estrategia Cloud

## Estado
Aceptado

## Contexto
Requerimientos técnicos indican necesidad de optimización de costes y escalabilidad, según el análisis de AI Architect.

## Decisión
{recommendation}

## Consecuencias
- Reducción de TCO en base a métricas calculadas.
- Despliegue automatizado gestionado vía Terraform provisto.
"""

    def _generate_dashboard(self, client_name: str, sections: List[Dict[str, Any]]) -> str:
        # En el MVP renderizaremos una plantilla HTML con JS embebido
        try:
            # Extraemos la simulación de la primera sección (Análisis de Costes)
            simulation_data = {}
            for sec in sections:
                if "metadata" in sec and "simulation" in sec["metadata"]:
                    simulation_data = sec["metadata"]["simulation"]
                    break

            template = self.env.get_template("dashboard.html.j2")
            return template.render(
                client_name=client_name, 
                sections=sections,
                simulation=simulation_data
            )
        except Exception as e:
            return f"<html><body><h1>Dashboard Error</h1><p>{str(e)}</p></body></html>"
    def _generate_roi_csv(self, sections: List[Dict[str, Any]]) -> str:
        """Genera un archivo CSV compatible con Excel para simulación financiera."""
        simulation = {}
        for sec in sections:
            if "metadata" in sec and "simulation" in sec["metadata"]:
                simulation = sec["metadata"]["simulation"]
                break
        
        csv_lines = [
            "Period,On-Premise ($),Cloud Native ($),Monthly Savings ($),Cumulative Savings ($)"
        ]
        
        cumulative = 0
        series = simulation.get("cashflow_series", [])
        for item in series:
            period = item.get("period", 0)
            onprem = item.get("onprem", 0)
            cloud = item.get("cloud", 0)
            savings = onprem - cloud
            cumulative += savings
            csv_lines.append(f"{period},{onprem},{cloud},{savings},{cumulative}")
            
        return "\n".join(csv_lines)

    def _generate_checklist(self, sections: List[Dict[str, Any]]) -> str:
        """Genera una lista de control operativa para el equipo técnico."""
        return """# Implementation Checklist: Cloud Transformation

## [ ] Phase 1: Foundation (Month 1-2)
- [ ] Deploy Immutable Audit Trail (PostgreSQL).
- [ ] Configure RBAC and IAM Roles for the delivery team.
- [ ] Validate regional compliance (DORA/GDPR).

## [ ] Phase 2: Hub Migration (Month 3-6)
- [ ] Execute Terraform main.tf deployment.
- [ ] Establish VPN/DirectConnect with on-premise baseline.
- [ ] Synchronize database mirrors.

## [ ] Phase 3: AI Ops Activation (Month 6+)
- [ ] Deploy Operational Nudges into the dashboard.
- [ ] Activate automated cost optimization scaling policies.
- [ ] Final hand-over to the business unit.
"""
